### ISSUE TITLE
Roadmap: Blender

### ISSUE THREAD

**Issue by sindharta** [Unity-Technologies/MeshSyncDCCPlugin#6]
- [x] fix visibility handling
- [x] fix parent handling
- [x] add 'bake transform' option
- [x] fix auto sync
- [ ] improve detecting updated objects (bpy.app.handlers.depsgraph_update_post)
- [ ] use render meshes (Subdivision modifier has both render/viewport iterations)
- [ ] fix bone handling (can reproduce by tree_creature.blend )
- [ ] handle textures
- [ ] materials
- [x] multiple uv support (https://github.com/unity3d-jp/MeshSync/issues/92).
Example:
Blender UV0 = DetailMapUV's = Unity UV0
Blender UV1 = LightMapUV's =Unity UV1
- [ ] send preview mesh when editing
- [ ] greasepen

**Comment by sasa42** [comment]
Hi. Great to see the work goes on.
I really miss  UV1 for an fantastic use case.

Blender UV0 = DetailMapUV's = Unity UV0
Blender UV1 = LightMapUV's =Unity UV1

**Comment by sasa42** [comment]
Hi. Is there any change to prioritize the multi uv support?

**Comment by sindharta** [comment]
@sasa42 Thank you for your question. 
MeshSyncDCCPlugin (and MeshSync) is a part of one whole system that we are developing, and unfortunately there are some other areas in this system that we are prioritizing at the moment.
We'll get back to this as soon as we can.

**Comment by sindharta** [comment]
@sasa42 Multi UV support for Blender has been released in version 0.3.2-preview.
You'll need to update both the MeshSync package for Unity, and MeshSyncDCCPlugins used by Blender
Please open an issue if you find a problem with it.

**Comment by bitinn** [comment]
gentle ping: Blender 3.1 is out today, probably need a version targeting it. (last I checked MeshSync plugin requires targeting Blender headers right?)

https://github.com/unity3d-jp/MeshSync/issues/24#issuecomment-416550364

**Comment by sindharta** [comment]
@bitinn Thank you for the ping. You are correct, the plugin uses Blender headers as include files..

**Comment by bitinn** [comment]
Sorry to ping again, but Blender 3.2 is out, would be great to have a version of MeshSync plugin targeting it (haven't tested current release yet, just assuming a new release is needed.)

**Comment by sindharta** [comment]
Yes, we'll need a new release for this. 
Thank you for the notification.

**Comment by bitinn** [comment]
@sindharta Hi, sorry to bother again, I know many work are now being done on MeshSync with Blender, will there be a minor release for Blender 3.2.1 before that work is completed? (since we don't have a release targeting 3.2 yet).

I would prefer not going through manual build process myself, but if we are pending for a major release then I would do that instead :)

**Comment by sindharta** [comment]
Blender 3.2 will be included in the next minor release (instead of patch release), which should happen this month if things go well.

**Comment by sindharta** [comment]
@bitinn Can you please try `MeshSync@0.14.2-preview` ?

**Comment by bitinn** [comment]
@sindharta I did, it worked, I need to test more about the unity -> blender GN sync, the GN parameters are sorted in alphabetical orders in Unity, that's probably something the Dublin team can address in future :)
